### PR TITLE
Add preprocessor sourcemap

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Review by dummdidumm — APPROVED** [review]

**Review by Conduitry — CHANGES_REQUESTED** [review]
This should be implemented in such a way that it does not fail with older versions of Svelte, and it doesn't look like this was done. The compiler throws an exception on unknown compiler options. If you have to bump the version of Svelte in order for existing tests to pass, then as implemented this is a breaking change.

**Comment by Conduitry** [comment]
Did the response from `svelte.preprocess` change in 3.30.0, of was the only change in `svelte.compile`? It may not have. The only way to do this might, unfortunately, be to check the `VERSION` of the copy of the compiler we're using. The other option is to update the `peerDependencies` and make this a major bump.

**Comment by benmccann** [comment]
I believe the response to `svelte.preprocess` did change in 3.30: 

https://github.com/sveltejs/svelte/pull/5584/files#diff-0807847b16925d369083bb663f10c695f477946c95824dc38aeb9a17969e52d7R223

**Comment by benmccann** [comment]
I think this should be okay because it would pass `sourcemap: undefined` on < 3.30. I didn't manually test that though. Do you still think this is something that I should take a closer look at?

**Comment by Conduitry** [comment]
The compiler throws if an unknown key is present in the options object, even if its value is `undefined`.

**Comment by benmccann** [comment]
updated. thanks for taking a look!

**Review by Conduitry — APPROVED** [review]

**Pull request merged**
