### PR TITLE
Handle sourcemaps

### PR DESCRIPTION
**Pull request by RedHatter**
Handle sourcemaps for when sveltejs/svelte#1863 is merged.

### CODE REVIEW

**Comment by benmccann** [comment]
@RedHatter I know this PR has been open awhile, but any chance you'd be able to rebase it?

**Comment by benmccann** [comment]
https://github.com/sveltejs/svelte/pull/5015 is pending to add sourcemap support in a synchronous manner based on the feedback on https://github.com/sveltejs/svelte/pull/1863 so this may soon be useful, which is why I was asking

**Comment by antony** [comment]
Depends on https://github.com/sveltejs/svelte/pull/5015 now

**Comment by lukeed** [comment]
@antony @benmccann Does this really _depend_ on the linked PR? I'm not sure, but I imagine this PR would still work fine before those changes land. Maybe @pngwn has some insight here since he's bashed head against preprocessors a bit

**Comment by benmccann** [comment]
Yeah, I don't think it depends on it and this behavior seems more correct, so I think it'd be nice to go ahead and merge this one.

It'd help make testing the svelte change slightly easier to get this one in. That PR btw might be https://github.com/sveltejs/svelte/pull/5428 which is a rebased version of the one Antony linked to

**Pull request merged**
