### PR TITLE
Make filename relative

### PR DESCRIPTION
**Pull request by benmccann**
My main motivation for this PR is that https://github.com/sveltejs/svelte/pull/4856 would embed the `filename` in the compiled code. I don't think that should be an absolute path because that makes it so that builds are not reproducible (e.g. compiled file will be different if you build in different directory or different machine), can leak information (e.g. my username is in my path), etc.

The `filename` is used in three existing places today:
* debug - I think relative path is easier to read for debugging and drops the redundant information
* sourcemap - the examples I see online use relative paths (e.g. [bugsnag article/tutorial](https://www.bugsnag.com/blog/source-maps)), so it seems like an improvement there
* passed to preprocess - I did an `npm link` of this PR against `svelte-preprocess` and all tests passed.

### CODE REVIEW

**Review by DominusVilicus — APPROVED** [review]
Looks good 👍

**Comment by lukeed** [comment]
Does this require https://github.com/sveltejs/svelte/pull/5476 parity?

**Comment by benmccann** [comment]
No. Other way around. I didn't want to merge that PR until we had this change

**Review by lukeed — APPROVED** [review]
I checked this out locally & applied it to a project using PostCSS and TypeScript preprocessing. Everything seems to check out well. 

Could not validate the claims made by the link `svelte` PR, but only because my test app is considerably smaller.

**Pull request merged**
