### PR TITLE
respect sourcemapExcludeSources when constructing map

### PR DESCRIPTION
**Pull request by alexdilley**

### CODE REVIEW

**Comment by benmccann** [comment]
@alexdilley we were trying to clear out the review queue on this repo today. It looks like this one will need to be rebased as a result

**Comment by antony** [comment]
Is there a way to verify this change? It's been submitted without a description/rationale nor any expectation of before and after, or what problem it solves.

**Comment by lukeed** [comment]
Hi @alexdilley – I know it's been a while (sorry!) but can you please check out the current code on `master`: https://github.com/sveltejs/rollup-plugin-svelte/blob/master/index.js#L338-L339

Instead of pushing `null`, it now skips the push entirely. I included tests for this, and don't see or know of any reason why `null` is preferred here.

If you could let me know, we'd appreciate that. Thanks!

**Comment by alexdilley** [comment]
Eek! Sorry I posted such a vague PR!! I'll come back to you with a response and more detail.

**Comment by alexdilley** [comment]
One quick follow-up, though... My interpretation of `sourcemapExcludeSources` is that it produces source map that doesn't expose source content, akin to `nosources-source-map` in Webpack:

> `nosources-source-map` - A SourceMap is created without the sourcesContent in it. It can be used to map stack traces on the client without exposing all of the source code. You can deploy the Source Map file to the webserver.

Do the changes you highlight, @lukeed, suggest that both the source content _as well as_ the source map are omitted?

(btw, great talk yesterday, @lukeed! I'm keen to look into freshie!)

**Comment by lukeed** [comment]
I think you're right! I just checked out Rollup's tests to see how it should be: https://github.com/rollup/rollup/tree/24fe07f39da8e4225f4bc4f797331930d8405ec2/test/form/samples/sourcemaps-excludesources/_expected

Looks like `sources` is OK to keep its file paths, but it sets `sourcesContent: null` in the output.

If you want to update this PR to fix that up, I'll get it in asap! Otherwise I can tweak it.

(Thank you 😃)

**Comment by lukeed** [comment]
I made the changes so that we now follow Rollup's lead – probably a good/safe example to follow 😆

**Review by lukeed — APPROVED** [review]
Thanks!

**Comment by alexdilley** [comment]
Awesome! Nice work, @lukeed. Thanks so much for getting this pushed through.

**Pull request merged**
