### PR TITLE
handle files with .svelte in the middle of their filename

### PR DESCRIPTION
**Pull request by Rich-Harris**
This slightly annoying bug was causing CI for https://github.com/sveltejs/hn.svelte.dev to fail

https://github.com/sveltejs/hn.svelte.dev/issues/20

### CODE REVIEW

**Comment by benmccann** [comment]
thank you, thank you!!

**Comment by Conduitry** [comment]
I could have sworn there was also an old issue for this in the Sapper repo that presumably should be closed now, but I cannot find it.

**Comment by antony** [comment]
@Conduitry found this one https://github.com/sveltejs/sapper/issues/668 but it's not the one I'm looking for. There is yet another one I can't find.

**Comment by antony** [comment]
Found it. https://github.com/sveltejs/sapper/issues/1050

**Pull request merged**
