### PR TITLE
Chore: Attach `uvu` runner

### PR DESCRIPTION
**Pull request by lukeed**
Replaces `mocha` with `uvu` – speed basically the same, but dependency tree much lighter

This PR is purposefully branching off `chore/testing` (#121) – recommend squashing this PR if/when merged.

### CODE REVIEW

**Comment by lukeed** [comment]
TravisCI failing with node 10.0 only – apparently `undefined` is returned for Node 10.x, but native `assert` _does_ allow this, which I find totally bonkers:

```js
assert.equal(null, undefined)
// => undefined (no error)
```

**Comment by pngwn** [comment]
I disapprove of this pull request. I want to keep seeing 400 of your head in the 'used by' section.

**Comment by lukeed** [comment]
I've stopped converting my repos for that very reason

**Comment by pngwn** [comment]
PRs inc.

**Comment by lukeed** [comment]
giphy

**Comment by benmccann** [comment]
I don't have a strong opinion about this one way or the other, but mocha's pretty widely used with lots of documentation and examples online, and I'm not sure the extra dependencies have any real negative effect

**Pull request merged**
